import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const courierPrime = localFont({
  variable: "--font-courier-prime",
  src: [
     {
        path: "../public/fonts/CourierPrime-Regular.woff2",
        weight: "400",
        style: "normal",
     },
  ],
});

const clashGrotesk = localFont({
  variable: "--font-clash-grotesk",
  src: [
     {
        path: "../public/fonts/ClashGrotesk-Regular.woff2",
        weight: "400",
        style: "normal",
     },
     {
        path: "../public/fonts/ClashGrotesk-Medium.woff2",
        weight: "500",
        style: "normal",
     },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashGrotesk.variable} ${courierPrime.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
