function getDateNDaysAgo(n: number): string {
   const date = new Date();
   date.setDate(date.getDate() - n);
   return date.toISOString();
}

export const mockDemoMovies = {
  genre: "DARK_COMEDY",
  logline: "A wedding planner sabotages her clients for Instagram fame.",
  review: "Savage humor with sharp social commentary.",
  sequelIdea: "She plans her own wedding—disaster strikes.",
  summary: "When love meets likes, chaos follows.",
  date: new Date().toISOString(),
};

export const getDemoMovies = (userId: string) => [
   {
      genre: "DARK_COMEDY",
      logline: "A wedding planner sabotages her clients for Instagram fame.",
      review: "Savage humor with sharp social commentary.",
      sequelIdea: "She plans her own wedding—disaster strikes.",
      summary: "When love meets likes, chaos follows.",
      date: getDateNDaysAgo(1),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline:
         "Two commuters share silent glances every morning on a crowded train.",
      review: "Heartfelt and slow-burning, like real love stories.",
      sequelIdea: "Years later, fate puts them on the same train again.",
      summary: "A love story told in eye contact and missed chances.",
      date: getDateNDaysAgo(2),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline: "Three roommates start a dinner club for strangers.",
      review: "Wholesome and funny, like a warm hug.",
      sequelIdea: "They expand globally through virtual dinners.",
      summary: "Food, laughter, and stories shared around the table.",
      date: getDateNDaysAgo(3),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline:
         "A firefighter uncovers a conspiracy while saving a burning skyscraper.",
      review: "Explosive action and emotional weight in equal measure.",
      sequelIdea: "His partner digs deeper into the conspiracy.",
      summary: "Fire isn’t the only thing that can kill.",
      date: getDateNDaysAgo(4),
      userId,
   },
   {
      genre: "FEEL_GOOD_MUSICAL",
      logline:
         "A cab driver starts singing with passengers to spread joy in the city.",
      review: "Delightful, with songs that stick in your head.",
      sequelIdea: "He takes the idea nationwide with a singing taxi fleet.",
      summary: "Sometimes the best ride comes with a song.",
      date: getDateNDaysAgo(5),
      userId,
   },
   {
      genre: "HORROR",
      logline:
         "A small town wakes up with mirrors that no longer reflect them.",
      review: "Creepy, thought-provoking, and hard to shake off.",
      sequelIdea: "They hunt for the one mirror that still shows the truth.",
      summary: "What happens when reflections fight back?",
      date: getDateNDaysAgo(6),
      userId,
   },
   {
      genre: "COMING_OF_AGE",
      logline:
         "A shy teen joins a pirate-themed summer camp to reinvent themselves.",
      review: "Funny, awkward, and full of heart.",
      sequelIdea: "They start a real crew years later as adults.",
      summary: "Growing up sometimes takes a little role-play.",
      date: getDateNDaysAgo(7),
      userId,
   },
   {
      genre: "ADVENTURE_FANTASY",
      logline:
         "A delivery drone gains sentience and dreams of becoming a hero.",
      review: "Weird but wonderful, with Pixar-like charm.",
      sequelIdea: "A new drone inherits the hero’s code.",
      summary: "Even machines can dream of legends.",
      date: getDateNDaysAgo(8),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline: "A divorced dad starts a babysitting vlog that goes viral.",
      review: "Sweet and funny, though some gags felt forced.",
      sequelIdea: "His book becomes a movie, causing new chaos.",
      summary: "Parenting isn’t easy, but it can be hilarious.",
      date: getDateNDaysAgo(9),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline:
         "Two chefs from rival restaurants compete for a Michelin star and fall in love.",
      review: "A delicious blend of passion and rivalry.",
      sequelIdea: "They travel the world cooking in street markets.",
      summary: "Love served hot, with a side of tension.",
      date: getDateNDaysAgo(10),
      userId,
   },
   {
      genre: "MYSTERY_SUSPENSE",
      logline:
         "A detective investigates a crime where the victim is still alive.",
      review: "Inventive concept with gripping tension.",
      sequelIdea: "The detective hunts copycats inspired by the case.",
      summary: "Some crimes refuse to stay dead.",
      date: getDateNDaysAgo(11),
      userId,
   },
   {
      genre: "FEEL_GOOD_MUSICAL",
      logline:
         "A grumpy landlord turns his building into a surprise musical theater.",
      review: "Unexpectedly heartwarming with show-stopping numbers.",
      sequelIdea: "They go on tour, turning cities into stages.",
      summary: "When walls echo with music, hearts open.",
      date: getDateNDaysAgo(12),
      userId,
   },
   {
      genre: "DARK_COMEDY",
      logline: "An influencer fakes their own kidnapping for clout.",
      review: "Disturbingly hilarious and very on-trend.",
      sequelIdea: "Other influencers start competing for extreme stunts.",
      summary: "When likes mean life or death.",
      date: getDateNDaysAgo(13),
      userId,
   },
   {
      genre: "COMING_OF_AGE",
      logline: "A teen forms a secret poetry club in detention.",
      review: "Tender and rebellious in the best way.",
      sequelIdea: "They start an underground art movement.",
      summary: "Breaking rules to find your voice.",
      date: getDateNDaysAgo(14),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline:
         "An ex-hacker is forced back online when their identity is stolen.",
      review: "Fast-paced and clever, though predictable in parts.",
      sequelIdea: "The hacker builds an AI to fight cybercrime.",
      summary: "One wrong click can change everything.",
      date: getDateNDaysAgo(15),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline:
         "A barbershop becomes the heart of neighborhood drama and dreams.",
      review: "Quietly profound with authentic characters.",
      sequelIdea: "They open branches across the city.",
      summary: "Ordinary days, extraordinary connections.",
      date: getDateNDaysAgo(16),
      userId,
   },
   {
      genre: "HORROR",
      logline:
         "Every night, a child’s drawings come alive and hunt the family.",
      review: "Creepy, imaginative, and deeply unsettling.",
      sequelIdea: "A new family inherits the cursed sketchbook.",
      summary: "Childhood imagination becomes a nightmare.",
      date: getDateNDaysAgo(17),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline: "A woman falls in love with the voice on a meditation app.",
      review: "Sweet and modern, with an unexpected emotional punch.",
      sequelIdea: "She builds an app to help others find love through audio.",
      summary: "Sometimes, love is just a voice away.",
      date: getDateNDaysAgo(18),
      userId,
   },
   {
      genre: "ADVENTURE_FANTASY",
      logline: "A retired knight starts a bed-and-breakfast for dragons.",
      review: "Whimsical and heartwarming with great world-building.",
      sequelIdea: "They expand to the underworld and host demons.",
      summary: "Where dragons come to rest and legends to relax.",
      date: getDateNDaysAgo(19),
      userId,
   },
   {
      genre: "MYSTERY_SUSPENSE",
      logline: "A city wakes up to find every clock frozen at the same time.",
      review: "Haunting and clever with a chilling twist.",
      sequelIdea: "A new mystery arises when time jumps forward 50 years.",
      summary: "When time stops, secrets surface.",
      date: getDateNDaysAgo(20),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline: "A failed magician starts performing at kids’ therapy sessions.",
      review: "Heartfelt and funny with great character depth.",
      sequelIdea: "He trains a team of misfit magicians.",
      summary: "Sometimes the biggest trick is healing.",
      date: getDateNDaysAgo(21),
      userId,
   },
   {
      genre: "DARK_COMEDY",
      logline:
         "An HR manager turns employee terminations into performance art.",
      review: "Wickedly funny, slightly terrifying.",
      sequelIdea: "They start a motivational speaking tour about layoffs.",
      summary: "When job cuts become a spectacle.",
      date: getDateNDaysAgo(22),
      userId,
   },
   {
      genre: "COMING_OF_AGE",
      logline:
         "A teen builds a robot to impress their crush, but it develops feelings too.",
      review: "Funny, heartfelt, and surprisingly deep.",
      sequelIdea: "The teen becomes a famous AI creator.",
      summary: "First love meets first code.",
      date: getDateNDaysAgo(23),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline:
         "An amnesiac wakes up in a self-driving car with a bomb set to detonate.",
      review: "Edge-of-your-seat action with tech paranoia.",
      sequelIdea: "He hunts the people who built the car.",
      summary: "When your ride becomes your prison.",
      date: getDateNDaysAgo(24),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline:
         "A lonely librarian starts leaving notes in books for strangers.",
      review: "Soft, warm, and hopeful.",
      sequelIdea: "They start a global kindness movement.",
      summary: "Small notes, big changes.",
      date: getDateNDaysAgo(25),
      userId,
   },
   {
      genre: "FEEL_GOOD_MUSICAL",
      logline: "A janitor turns the night shift into a secret dance party.",
      review: "Pure joy with dazzling choreography.",
      sequelIdea: "They take the dance party to other cities.",
      summary: "Cleaning floors, breaking norms.",
      date: getDateNDaysAgo(26),
      userId,
   },
   {
      genre: "HORROR",
      logline: "A haunted VR game traps players in their worst memories.",
      review: "Inventive and terrifying with strong psychological horror.",
      sequelIdea: "A new version of the game leaks years later.",
      summary: "Virtual nightmares become real.",
      date: getDateNDaysAgo(27),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline:
         "Two patients in a recovery center fall in love through anonymous letters.",
      review: "Bittersweet and tender.",
      sequelIdea: "The survivor starts a letter therapy program.",
      summary: "Healing hearts, one note at a time.",
      date: getDateNDaysAgo(28),
      userId,
   },
   {
      genre: "MYSTERY_SUSPENSE",
      logline:
         "An artist’s paintings start depicting crimes before they happen.",
      review: "Creepy, tense, and full of twists.",
      sequelIdea: "A copycat starts forging predictive paintings.",
      summary: "Art that kills before the brush dries.",
      date: getDateNDaysAgo(29),
      userId,
   },
   {
      genre: "ADVENTURE_FANTASY",
      logline:
         "A talking map guides a lonely traveler through a cursed kingdom.",
      review: "Epic and heartfelt with clever humor.",
      sequelIdea: "The traveler becomes the map for someone else.",
      summary: "Not all guides are alive—but some care the most.",
      date: getDateNDaysAgo(30),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline: "A therapist starts using stand-up comedy in sessions.",
      review: "Smart, funny, and surprisingly moving.",
      sequelIdea: "They open a comedy-club-slash-therapy-center.",
      summary: "Laughing through the pain, literally.",
      date: getDateNDaysAgo(31),
      userId,
   },
   {
      genre: "FEEL_GOOD_MUSICAL",
      logline: "A shy accountant turns their spreadsheets into rap songs.",
      review: "Quirky and fun, though niche humor might not hit for all.",
      sequelIdea: "They become a financial influencer with music tutorials.",
      summary: "Balancing books while dropping beats.",
      date: getDateNDaysAgo(32),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline:
         "A flight attendant stops a hijacking mid-air using only snacks and charm.",
      review: "Tense with comedic relief in the right places.",
      sequelIdea: "Her next flight is a covert mission.",
      summary: "When peanuts become weapons.",
      date: getDateNDaysAgo(33),
      userId,
   },
   {
      genre: "DARK_COMEDY",
      logline: "A man starts attending strangers’ funerals for free food.",
      review: "Dark, ironic, and weirdly relatable.",
      sequelIdea: "He hosts a podcast about funerals gone wrong.",
      summary: "Crashing funerals for a taste of life.",
      date: getDateNDaysAgo(34),
      userId,
   },
   {
      genre: "COMING_OF_AGE",
      logline:
         "A teen finds their voice by starting an illegal pirate radio station.",
      review: "Empowering and nostalgic, with great music.",
      sequelIdea: "They start a podcast empire as adults.",
      summary: "Broadcasting rebellion, one song at a time.",
      date: getDateNDaysAgo(35),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline:
         "Two rival bookshop owners fight for customers and fall for each other.",
      review: "Classic setup done with modern charm.",
      sequelIdea:
         "They host an annual book festival that sparks more love stories.",
      summary: "Love written in the margins.",
      date: getDateNDaysAgo(36),
      userId,
   },
   {
      genre: "HORROR",
      logline:
         "An elevator gets stuck between floors with something alive in the shadows.",
      review: "Claustrophobic and terrifying.",
      sequelIdea: "A whole building becomes sentient.",
      summary: "Some rides never end.",
      date: getDateNDaysAgo(37),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline: "An elderly man starts a morning jogging group to make friends.",
      review: "Heartwarming and real.",
      sequelIdea: "The group expands into a senior adventure club.",
      summary: "Friendship one step at a time.",
      date: getDateNDaysAgo(38),
      userId,
   },
   {
      genre: "ADVENTURE_FANTASY",
      logline: "A baker discovers their bread has magical powers.",
      review: "Sweet and enchanting with cozy vibes.",
      sequelIdea: "They start a bakery for enchanted beings.",
      summary: "Magic, yeast, and destiny.",
      date: getDateNDaysAgo(39),
      userId,
   },
   {
      genre: "MYSTERY_SUSPENSE",
      logline: "Every night, a woman wakes up in a different stranger’s life.",
      review: "Mind-bending and gripping.",
      sequelIdea: "Others begin experiencing the same phenomenon.",
      summary: "When identity becomes a ticking clock.",
      date: getDateNDaysAgo(40),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline:
         "Two rival ice cream truck drivers battle for the hottest route.",
      review: "Sweet and silly with heartfelt undertones.",
      sequelIdea: "They take the rivalry to food festivals worldwide.",
      summary: "Chill vibes with a sprinkle of chaos.",
      date: getDateNDaysAgo(41),
      userId,
   },
   {
      genre: "FEEL_GOOD_MUSICAL",
      logline:
         "A group of exhausted nurses turns the hospital into a musical stage.",
      review: "Inspiring and fun with powerful messages.",
      sequelIdea: "They tour other hospitals spreading joy.",
      summary: "Healing through harmony.",
      date: getDateNDaysAgo(42),
      userId,
   },
   {
      genre: "DARK_COMEDY",
      logline: "A hitman starts a children’s puppet show as a cover.",
      review: "Absurd, hilarious, and violent in equal measure.",
      sequelIdea: "He takes the show international while hiding bodies.",
      summary: "Strings attached in all the wrong places.",
      date: getDateNDaysAgo(43),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline:
         "A chef must save a restaurant full of hostages during a dinner rush.",
      review: "Intense, unique setting for action fans.",
      sequelIdea: "He becomes a culinary bodyguard for celebrity chefs.",
      summary: "Knife skills put to deadly use.",
      date: getDateNDaysAgo(44),
      userId,
   },
   {
      genre: "HORROR",
      logline: "A baby monitor starts broadcasting from another dimension.",
      review: "Chilling and fresh take on parenting horror.",
      sequelIdea: "The entity wants to raise the human baby in its world.",
      summary: "Every sound has a secret.",
      date: getDateNDaysAgo(45),
      userId,
   },
   {
      genre: "COMING_OF_AGE",
      logline:
         "A high school gamer starts a real-life treasure hunt to prove themselves.",
      review: "Fun and heartfelt with strong characters.",
      sequelIdea: "They organize global gaming treasure hunts.",
      summary: "Leveling up in life, not just the game.",
      date: getDateNDaysAgo(46),
      userId,
   },
   {
      genre: "ACTION_THRILLER",
      logline:
         "A single dad runs a dog-walking business to spend more time with his kid.",
      review: "Heartwarming with gentle humor.",
      sequelIdea: "They franchise the dog-walking service.",
      summary: "Love and loyalty on every leash.",
      date: getDateNDaysAgo(47),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline:
         "Two strangers share an umbrella during a storm and never exchange names.",
      review: "Poetic and emotional with lingering tension.",
      sequelIdea: "They start a romance advice podcast together.",
      summary: "A love story born from rain.",
      date: getDateNDaysAgo(48),
      userId,
   },
   {
      genre: "MYSTERY_SUSPENSE",
      logline: "A hotel only has guests who all look like the same person.",
      review: "Creepy and mind-bending with surreal tones.",
      sequelIdea: "A new hotel opens with even more secrets.",
      summary: "Checking in to your own nightmare.",
      date: getDateNDaysAgo(49),
      userId,
   },
   {
      genre: "ADVENTURE_FANTASY",
      logline: "A fisherman reels in a mermaid who wants to become a pirate.",
      review: "Funny and fantastical with vibrant settings.",
      sequelIdea: "They hunt for treasure that controls the seas.",
      summary: "When the catch of the day changes destiny.",
      date: getDateNDaysAgo(50),
      userId,
   },
   {
      genre: "COMEDY_DRAMA",
      logline: "An overworked lawyer starts doing stand-up at night to cope.",
      review: "Sharp, funny, and painfully honest.",
      sequelIdea: "The club becomes a movement for mental health.",
      summary: "Finding humor in the chaos of life.",
      date: getDateNDaysAgo(51),
      userId,
   },
];
